---
- name: Checkout site data
  git:
    clone: yes
    depth: 1
    dest: "{{ git_dir }}"
    repo: "{{ origin_remote }}"
    force: yes
  notify:
    - Restart Nginx

- name: Ensure needed packages installed
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-pip
    - python3-venv
    - libjpeg-turbo-progs
    - npm
    - nodejs
    - sshpass

- name: Install svgo
  npm:
    name: svgo
    global: yes

- name: Install python dependencies into virtualenv
  pip:
    requirements: "{{ git_dir }}/requirements.txt"
    virtualenv: "{{ venv_dir }}"
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv_site_packages: no

- name: Overwrite sensitive settings
  template:
    src: sensitive_settings.py
    dest: "{{ git_dir }}/sensitive_settings.py"
    mode: 0644
    owner: root
    group: root

- name: Install pelican themes
  git:
    clone: yes
    depth: 1
    dest: "{{ git_dir }}/pelican-themes"
    repo: https://github.com/getpelican/pelican-themes.git
    recursive: no
    force: yes

- name: Install pelican plugins
  git:
    clone: yes
    depth: 1
    dest: "{{ git_dir }}/pelican-plugins"
    repo: https://github.com/getpelican/pelican-plugins.git
    recursive: no
    force: yes

- name: Render pages
  command: "{{ venv_dir }}/bin/pelican content -s publishconf.py"
  args:
    chdir: "{{ git_dir }}"

- name: Ensure target directories
  file:
    path: "/var/www/{{ blog_hostname }}"
    state: directory

- name: Recursively copy output files
  synchronize:
    src: "{{ git_dir }}/output/"
    dest: "/var/www/{{ blog_hostname }}/"
  delegate_to: "{{ inventory_hostname }}"
